#spring:
#  application:
#    name: site
#  datasource:
#    url: jpa:postgresql://localhost:5432/it_one_db?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
#    username: ${DB_USERNAME}
#    password: ${POSTGRES_PASSWORD}
#    driverClassName: org.postgresql.Driver
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#      database: postgresql
#      properties:
#        hibernate:
#          dialect: org.hibernate.dialect.Pos\tgreSQLDialect
#          format_sql: true
#    show-sql: true

spring:
  application:
    name: itotdel

server:
  port: 8080

itotdel:
  members:
    - name: Lev
      last_name: Stremilov
      age: 18
      stream: backend developer
    - name: test
      last_name: test
      age: 12
      stream: pozer