spring:
  application:
    name: money
  datasource:
    url: jdbc:postgresql://localhost:5432/it_one_db?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
      database: postgresql
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: true
    show-sql: true

server:
  port: 8080

fake_db:
  members:
    - name: Lev
      last_name: Stremilov
      age: 18
    - name: test
      last_name: test
      age: test